config/routes.rb
Goodlist::Application.routes.draw do
  devise_for :users
  resources :places do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  get "about" => 'pages#about'

  root 'pages#welcome'

end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :user
	
	has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places, dependent: :destroy
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def welcome
  	@places = Place.all
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  def upvote
    @place = Place.find(params[:id])
    @place.votes.create
    redirect_to(root_path)
  end

  def downvote
    @place = Place.find(params[:id])
    @place.votes.first.destroy
    redirect_to(root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :image, :kind, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Goodlist: shop socially smart</title>
	  
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>
	
  </head>
	
  <body>
   <div class="container"> 
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Goodlist", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "About", about_url %></li> 
            <li><%= link_to "Top Places", places_url %></li>  
          </ul> 
          <ul class="nav navbar-nav navbar-right">   
            <% if user_signed_in? %>
              <li>
                <%= link_to new_place_path do %>
                  <span class="glyphicon glyphicon-plus"></span> New place
                <% end %>
              </li>
              <li>
                <%= link_to "My Settings", edit_user_registration_path %></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
              <% else %>
                <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %> 
          </ul>
      
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
	<div class="container">
		<p>Goodlist spotlights socially responsible businesses and allows users to do the same. </p>
		<p>-Tim Killeen, Founder</p>
	</div>
</div>
<div class="container">
	<p>Code by <%= link_to "Chad Flores", "https://twitter.com/chadpflores" %> of <%= link_to "BuildRed", "http://buildred.co" %></p>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50127268-1', 'goodlist.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/pages/welcome.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Shop socially smart</h1>
		<p class="lead">Post your favorite places to shop, eat, and drink. Share the love with the businesses to let them know you care.</p>
		<% if user_signed_in? %>
		<% else %>
			<p>
			<%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-inverse btn-lg" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-default btn-lg" %>
			</p>
		<% end %>	
	</div>
</div>

<div class="container">
	<% @places.each do |place| %>
		<%= render 'places/place', place: place %>
		<br>
		<br>
		<br>
	<% end %>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50127268-1', 'goodlist.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Name %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :Image_Link %><br>
    <%= f.text_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :Kind %><br>
    <%= f.select :kind, ["Eat", "Drink", "Shop"], {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :Description %><br>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Publish", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/places/_place.html.erb
<div class="row">
	<div class="col-md-1">
		<p><%= button_to '+1', upvote_place_path(place), method: :post, class: "btn btn-primary btn-lg" %></p>
		<h3 class="vote-count"><%= pluralize(place.votes.count, "♥") %></h3>
		<p><%= button_to '-1', downvote_place_path(place), method: :post, class: "btn btn-primary btn-lg" %></p>
	</div>
	<div class="col-md-5">
		<%= image_tag place.image, style: "width: 100%" %>	
		
	</div>
	<div class="col-md-6">
	<p>  
		<%= place.kind %> // 
	</p>
	<p><h2><%= link_to place.title, place %></h2></p>
	<p><h3><%= simple_format place.content %></h3></p>
	
	<p class="text_muted">
		<small>Posted at <%= place.created_at.to_formatted_s(:long) %></small>
	</p>
</div>
</div>

app/views/places/edit.html.erb
<div class="container">

<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %> | 

</div>

app/views/places/index.html.erb
<div class="container">

<div class="page-header">
  <h1>Goodlist Top Places</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Votes</th>
      <th>Place</th>
      <th>Why is it Good?</th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.votes.count %></td>
        <td><%= link_to place.title, place %></td>
        <td><%= truncate(place.content, length: 100) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Place', new_place_path %>

</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50127268-1', 'goodlist.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/places/new.html.erb
<div class="container">

<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

</div>

app/views/places/show.html.erb
<div class="container">

<%if notice.present? %>
	<p class="alert alert-info">
		<%= notice %>
	</p>
<% end %>

	<p>  
		<%= @place.kind %> // 
	</p>
	<p class="text_muted">
		<small>Posted at <%= @place.created_at.to_formatted_s(:long) %></small>
	</p>
	<p><h2><%= link_to @place.title, @place %></h2></p> 
	<p><h3><%= simple_format @place.content %></h3></p>
	
	<p><%= image_tag @place.image, style: "width: 100%" %></p>	
	
	
<p>
<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Delete', @place, method: :delete, data: { confirm: 'Are you sure?' } %> 
</p>
<p>
<%= link_to 'Back', root_path %>
</p>
</div>